name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.1

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build (turbo)
        run: pnpm -w build

      - name: Lint
        run: pnpm -w lint || true

      - name: Unit tests (vitest)
        run: pnpm -w test -- --run

      - name: Size budget (injector)
        run: pnpm -w --filter @webexp/injector build && pnpm -w --filter @webexp/injector size
